services:
  frontend:
    depends_on: 
      - backend
    build: ./frontend
    ports:
      - 5173:5173
    volumes :
      - ./frontend:/app
  backend: 
    build: ./backend
    ports: 
      - 4000:4000
    environment: 
      MONGODB_URI: mongodb+srv://sandheep:sandheep@legionfitness.1rayd.mongodb.net/
    volumes :
      - ./backend:/app
    